# dashboard/datos_cualitativos.py

BRECHAS = [
    {'nivel': '4° básico', 'asignatura': 'Matemática', 'curso_a': '4° A (55.7%)', 'curso_b': '4° B (48.4%)', 'brecha': 7.3, 'lectura': 'Brecha alta: revisar planificación, evaluación común.'},
    {'nivel': '6° básico', 'asignatura': 'Matemática', 'curso_a': '6° A (35.7%)', 'curso_b': '6° B (44.5%)', 'brecha': 8.8, 'lectura': 'Brecha alta: revisar planificación y práctica.'},
    {'nivel': 'II° medio', 'asignatura': 'Matemática', 'curso_a': '2° Medio A (31.0%)', 'curso_b': '2° Medio B (30.6%)', 'brecha': 0.4, 'lectura': 'Problema homogéneo crítico.'},
    {'nivel': '4° básico', 'asignatura': 'Lenguaje', 'curso_a': '4° A (63.4%)', 'curso_b': '4° B (55.5%)', 'brecha': 7.9, 'lectura': 'Brecha alta: revisar planificación y práctica.'},
    {'nivel': '6° básico', 'asignatura': 'Lenguaje', 'curso_a': '6° A (61.6%)', 'curso_b': '6° B (55.8%)', 'brecha': 5.8, 'lectura': 'Brecha menor. Problema más homogéneo.'},
    {'nivel': 'II° medio', 'asignatura': 'Lenguaje', 'curso_a': '2° Medio A (53.7%)', 'curso_b': '2° Medio B (46.8%)', 'brecha': 6.9, 'lectura': 'Brecha alta: revisar evaluación.'},
]

ALERTAS = [
    {'nivel': 'Alto', 'criterio': 'Estudiante <40% o curso <40%', 'accion': 'Plan individual/grupal, reforzamiento obligatorio, entrevista familia, seguimiento semanal.', 'frecuencia': 'Semanal'},
    {'nivel': 'Medio', 'criterio': 'Estudiante 40%-55% o curso 40%-50%', 'accion': 'Grupo de nivelación, práctica guiada y evaluación quincenal.', 'frecuencia': 'Quincenal'},
    {'nivel': 'Institucional', 'criterio': '>15 preguntas bajo 40%', 'accion': 'Reenseñanza de OA críticos y revisión de cobertura curricular.', 'frecuencia': 'Quincenal'},
]

PLAN_ACCION = [
    {'plazo': '30 días', 'foco': 'Matemática II° medio', 'accion': 'Plan de rescate matemático: nivelación de habilidades basales, 3 bloques semanales y miniensayos de 10-15 ítems.', 'resp': 'UTP / Depto. Matemática'},
    {'plazo': '30 días', 'foco': '6° A Matemática', 'accion': 'Reenseñanza focalizada en números, fracciones, decimales y resolución de problemas.', 'resp': 'UTP / Docente'},
    {'plazo': '30 días', 'foco': 'II° B Lenguaje', 'accion': 'Rutina de lectura estratégica con foco en inferencia, vocabulario y argumentación.', 'resp': 'UTP / Depto. Lenguaje'},
    {'plazo': '60 días', 'foco': 'Evaluaciones comunes', 'accion': 'Aplicar evaluación común por nivel y asignatura en cursos críticos.', 'resp': 'UTP'},
    {'plazo': '60 días', 'foco': 'Observación de aula', 'accion': 'Observación focalizada a Matemática y Lenguaje con retroalimentación.', 'resp': 'Rectoría / UTP'},
    {'plazo': '90 días', 'foco': 'Nuevo ensayo', 'accion': 'Comparar contra línea base de mayo y ajustar intervención.', 'resp': 'Rectoría / UTP'},
]

INFORMES_CURSOS = {
    "4° A_LEN": {
        "resultados_generales": "Este análisis de ensayo SIMCE en lenguaje evidencia un rendimiento promedio de 246 puntos SIMCE y un logro global de 63,4%, lo que muestra un desempeño intermedio, con fortalezas claras en identificación de información explícita, pero importantes brechas en análisis, interpretación y vocabulario en contexto.",
        "habilidades_labels": ["Identificar", "Interpretar", "Analizar"],
        "habilidades_data": [73.6, 54.5, 54.2],
        "fortalezas": ["Textos no literarios (Infografía/Afiche): 80,6%", "Textos literarios líricos: 75%", "Habilidad de identificar: 73,6%", "Logran localizar información explícita y comprenden textos breves con apoyo visual."],
        "debilidades": ["Analizar: 54,2%", "Interpretar: 54,5%", "Narrativa: 56,4%", "Dificultades en inferencias, comprensión global, deducción de ideas implícitas y lenguaje figurado."],
        "contenidos_labels": ["Infografías", "Líricos", "Narrativos", "Vocabulario"],
        "contenidos_data": [80.6, 75.0, 56.4, 54.5],
        "preguntas_criticas": "Las preguntas críticas fueron P13 (18,2%), P24 (21,2%) y P6 (27,3%). Se concentran en el eje de Narrativa y en la habilidad de analizar motivaciones de personajes y vocabulario en contexto.",
        "analisis_estudiantes": "Se evidencia un grupo destacado (Diego Bustamante, Elizabeth González, Joaquín Sandoval) que supera los 330 puntos. En contraste, estudiantes como Joaquín Jara (100 pts) y Antonia Manzano (114 pts) requieren intervención focalizada y lectura guiada urgente.",
        "estudiantes_nombres": ["D. Bustamante", "E. González", "J. Sandoval", "S. Díaz", "J. Porra", "J. Jara"],
        "estudiantes_puntajes": [400, 346, 330, 182, 126, 100],
        "estrategias": [
            "Trabajo focalizado en inferencias: Aplicar diariamente preguntas como ¿Por qué el personaje actuó así?, ¿Qué habrá sentido?, ¿Qué podría pasar después?",
            "Fortalecer vocabulario en contexto: Uso de 'La palabra del día', subrayado contextual y mapas semánticos.",
            "Rutina semanal tipo SIMCE: 2 mini ensayos semanales de 5 a 8 preguntas con corrección y análisis de distractores.",
            "Enseñanza explícita de habilidades: Modelo 'Yo hago -> Nosotros hacemos -> Tú haces'.",
            "Lectura oral modelada: Fomentar lectura compartida y dramatizada para mejorar fluidez y comprensión profunda.",
            "Trabajo diferenciado por grupos: Grupo bajo (literal y fluidez), Grupo medio (inferencias), Grupo avanzado (análisis y argumentación)."
        ],
        "plan_accion_sugerido": [
            "Implementar Plan lector transversal en Historia, Ciencias y Orientación.",
            "Aplicar mini ensayo mensual y análisis por habilidad desde UTP.",
            "Trabajo de retroalimentación docente para construcción de preguntas tipo SIMCE.",
            "Vinculación con familias: enviar cápsulas de lectura y exigir 15 minutos diarios de lectura compartida en el hogar."
        ],
        "actividades_aplicables": [
            "Actividad '¿Qué quiso decir?': Subrayar pistas de textos breves para interpretar información implícita (10 min diarios).",
            "Actividad 'Detectives de pistas': El alumno responde, encuentra la frase que le dio la pista y la explica oralmente.",
            "Actividad 'Ordena la historia': Entregar secuencias desordenadas para comprender la estructura narrativa.",
            "Actividad 'La palabra escondida': Inferir significados por contexto, crear sinónimos y usar la palabra en nuevas oraciones.",
            "Viernes SIMCE: 1 texto y 5 preguntas con corrección grupal explicando por qué los distractores son incorrectos.",
            "Semáforo lector: Uso de tarjetas de colores para monitorear metacognición durante la lectura.",
            "En los zapatos del personaje: Analizar intenciones y crear un 'Diario de vida del personaje'.",
            "Lectura pensada: Modelamiento donde el docente lee y verbaliza cómo piensa un lector experto.",
            "Parejas lectoras: Unir a un estudiante fuerte con uno descendido para apoyo entre pares."
        ],
        "conclusion": "La meta realista es subir entre 20 y 30 puntos (llegando a 265-275 pts) si existe intervención sistemática en inferencia y vocabulario."
    },
    "4° B_LEN": {
        "resultados_generales": "El 4° Básico B presenta un promedio SIMCE de 263,4 puntos y un logro global de 55,5%, evidenciando un curso con potencial de mejora, pero con debilidades importantes en comprensión profunda, interpretación y narraciones literarias. A diferencia del 4° A, este curso posee un promedio SIMCE más alto, pero un menor porcentaje de logro global, lo que muestra un grupo más disperso: algunos estudiantes con muy buen rendimiento y otros con resultados extremadamente bajos.",
        "habilidades_labels": ["Identificar", "Evaluar", "Interpretar", "Analizar", "Comprender"],
        "habilidades_data": [65.7, 57.1, 50.9, 50.6, 46.8],
        "fortalezas": ["Poemas: 70,1%", "Buena comprensión literal, reconocimiento de emociones, interpretación básica del lenguaje figurado.", "Identificar: 65,7% (encuentra información explícita)."],
        "debilidades": ["Narraciones literarias: 50,7%", "Comprender: 46,8%", "Falta de comprensión profunda, ideas implícitas, propósito del texto y secuencia narrativa."],
        "contenidos_labels": ["Poemas", "Informativos", "Narrativos", "Vocabulario"],
        "contenidos_data": [70.1, 58.3, 50.7, 51.4],
        "preguntas_criticas": "Preguntas con peores resultados: P31 (5,6%), P24 (11,1%), P6 (19,4%), P23 (27,8%). Corresponden a inferencia global, deducción de consecuencias, vocabulario abstracto y lenguaje figurado complejo.",
        "analisis_estudiantes": "Curso con gran heterogeneidad. Estudiantes prioritarios: Pedro Fuentes (156), Diego Painemilla (188), Dominga Troncoso (188), Sara Bobadilla (208), Mateo Reyes (215), Máximo Rubio (215).",
        "estudiantes_nombres": ["M. Reyes", "S. Bobadilla", "D. Troncoso", "D. Painemilla", "P. Fuentes"],
        "estudiantes_puntajes": [215, 208, 188, 188, 156],
        "estrategias": [
            "Trabajo intensivo en comprensión profunda: Implementar estrategia 'Pienso mientras leo' para enseñar cómo piensa un lector experto.",
            "Fortalecer narraciones literarias: Ordenar eventos, analizar personajes ('¿por qué actuó así?') y proponer cambios de finales.",
            "Enseñanza explícita de inferencias en rutina diaria: Preguntar siempre '¿Cómo lo sabes?' y '¿Qué pistas entrega el texto?'.",
            "Trabajo fuerte en vocabulario contextual: Aplicar la 'Palabra del día' y 'Detectives de palabras'.",
            "Mini ensayos semanales: 2 veces por semana analizando minuciosamente los distractores.",
            "Fluidez lectora diaria: Fomentar lectura coral, repetida y dramatizada para alumnos con baja automatización."
        ],
        "plan_accion_sugerido": [
            "Plan lector diario de 15 minutos obligatorios.",
            "Monitoreo quincenal UTP con seguimiento exclusivo a estudiantes descendidos.",
            "Vinculación con familias enviando lectura semanal con preguntas inferenciales.",
            "Aplicar propuesta de rutina: Lunes (Inferencias), Martes (Narraciones), Miércoles (Vocabulario), Jueves (Ítems SIMCE), Viernes (Mini ensayo)."
        ],
        "actividades_aplicables": [
            "Actividad 'Pienso mientras leo': Docente verbaliza sus deducciones al leer en voz alta.",
            "Actividad '¿Qué no dice el texto?': Deducir emociones e información implícita de textos breves.",
            "Mapa de la historia: Completar cartulina con Inicio, Problema, Desarrollo, Solución y Final.",
            "Desarmando preguntas: Leer una pregunta SIMCE crítica en conjunto, buscar evidencia y descartar distractores.",
            "Actividad 'La pregunta del día': 5 minutos diarios con una pregunta inferencial rápida.",
            "Actividad de lectura repetida: Leer un párrafo 3 veces para mejorar la velocidad.",
            "Actividad 'Dibuja lo que entendiste': Para verificar comprensión en estudiantes con dificultades severas.",
            "Cadena de eventos: Escribir el hecho, su consecuencia y el nuevo problema que genera.",
            "Actividad metacognitiva '¿Cómo encontré la respuesta?': Explicar el razonamiento al curso."
        ],
        "conclusion": "El 4° Básico B tiene el potencial para alcanzar los 280-290 puntos si se logra nivelar al grupo de riesgo crítico y se consolida la comprensión profunda de textos narrativos mediante metodologías de aula estructuradas."
    },
    "4° A_MAT": {
        "resultados_generales": "Según los resultados obtenidos en la evaluación SIMCE de Matemática aplicada al 4°A, el curso presenta un 55,7% de logro global y una proyección de 274,3 puntos SIMCE, con 33 estudiantes evaluados.",
        "habilidades_labels": ["Patrones/Álgebra", "Números", "Medición", "Geometría", "Datos/Prob."],
        "habilidades_data": [64.4, 60.6, 59.6, 44.2, 34.8],
        "fortalezas": ["Patrones y Álgebra: 64,4%", "Números y Operaciones: 60,6%", "Medición: 59,6%", "Valor posicional y representación de números: 90,9%", "Figuras 3D: 97%", "Resolución de ecuaciones simples: 84,8%"],
        "debilidades": ["Datos y Probabilidades: 34,8%", "Geometría: 44,2%", "Analizar: 38,3%", "Dificultad evidente al interpretar datos, analizar situaciones y resolver preguntas de mayor complejidad cognitiva."],
        "contenidos_labels": ["Álgebra", "Números", "Geometría", "Datos"],
        "contenidos_data": [64.4, 60.6, 44.2, 34.8],
        "preguntas_criticas": "P10 (9,1%), P23 (12,1%), P20 (15,2%). Focalizadas en lectura de gráficos de barra doble y problemas de varios pasos.",
        "analisis_estudiantes": "Estudiantes con seguimiento focalizado urgente (proyectados bajo 245 pts): Julián Mesa (208), Agustín Gajardo (221), Juan José Porra (221), Sebastián Díaz (238), Benjamín Ovalle (244), Maite Méndez (249).",
        "estudiantes_nombres": ["B. Ovalle", "S. Díaz", "A. Gajardo", "J. Porra", "J. Mesa"],
        "estudiantes_puntajes": [244, 238, 221, 221, 208],
        "estrategias": [
            "Estrategias de Geometría (OA 15 y OA 18): Construcción de cubos con plantillas, desplegar cuerpos y búsqueda de ángulos en la sala.",
            "Estrategias de Datos (OA 27): Lectura diaria de gráficos y elaboración de encuestas reales del curso.",
            "Estrategias de cálculo mental: Rutina diaria de 10 minutos con descomposición, dobles y mitades."
        ],
        "plan_accion_sugerido": [
            "Corto plazo (1 mes): 15 minutos diarios de cálculo mental, 2 talleres semanales de geometría y lectura de gráficos.",
            "Mediano plazo (2 a 4 meses): Ensayos quincenales y corrección colectiva de errores.",
            "Creación de un cuaderno de estrategias matemáticas.",
            "Trabajo diferenciado con estudiantes bajo 250 puntos proyectados."
        ],
        "actividades_aplicables": [
            "Rutina 'Desafío Matemático' (10 min): Encontrar errores en operaciones ya resueltas.",
            "Taller Geometría Manipulativa: Armar figuras 3D con cartulina y dibujar su red.",
            "Caza de Ángulos: Recorrer el colegio fotografiando y clasificando ángulos reales.",
            "Periodistas Matemáticos: Realizar encuesta semanal del curso, construir el gráfico y responder preguntas tipo SIMCE.",
            "Diagramas Humanos: Los estudiantes forman un diagrama de puntos gigante ubicándose en la sala.",
            "Estaciones Matemáticas: Rotación cada 12 minutos (Cálculo, Problemas, Geometría, Gráficos).",
            "Estrategia de los 4 pasos para problemas: Leer, Subrayar datos, Pensar operación, Comprobar.",
            "Juego 'Detective Matemático': Analizar una afirmación incorrecta sobre un gráfico y justificar el error.",
            "La Feria Matemática: Proyecto integrado donde encuestan, grafican y construyen figuras."
        ],
        "conclusion": "La meta es subir la habilidad de analizar sobre un 55%. Al consolidar el trabajo con gráficos y problemas de múltiples pasos, el curso superará sin problemas la barrera de los 285 puntos."
    },
    "4° B_MAT": {
        "resultados_generales": "El curso obtuvo un logro global de 48,4% y un puntaje SIMCE estimado de 255,6 puntos, ubicándose en un nivel de desempeño intermedio, aunque con importantes brechas internas entre estudiantes. Se observa que menos de la mitad de las respuestas fueron correctas, lo que evidencia la necesidad de fortalecer habilidades matemáticas de orden superior, especialmente aquellas relacionadas con la resolución de problemas y el análisis de información.",
        "habilidades_labels": ["Representar", "Identificar", "Calcular", "Analizar", "Aplicar"],
        "habilidades_data": [63.3, 56.9, 48.2, 37.9, 33.6],
        "fortalezas": ["Representar: 63,3%", "Identificar: 56,9%", "Medición: 60,4%", "Los estudiantes logran reconocer información matemática, interpretar representaciones y trabajar adecuadamente con modelos concretos y pictóricos."],
        "debilidades": ["Aplicar: 33,6%", "Analizar: 37,9%", "Datos y Probabilidades: 35,2%", "La principal dificultad está en utilizar los conocimientos matemáticos para resolver situaciones nuevas y analizar información para tomar decisiones."],
        "contenidos_labels": ["Medición", "Patrones", "Geometría", "Datos"],
        "contenidos_data": [60.4, 55.5, 49.4, 35.2],
        "preguntas_criticas": "Pregunta P16 (12,5%), P22 (15,6%) y P30 (15,6%). Se relacionan con diagramas, problemas combinados de suma/resta y análisis geométrico.",
        "analisis_estudiantes": "Destacan: Jorge Jara, Cristóbal Prado y Benjamín Véjar (340 pts). En riesgo crítico (bajo 160 pts): Máximo Benavides, Isidora Cisternas, Pedro Fuentes y Rocío Campos. Requieren evaluación de necesidades educativas.",
        "estudiantes_nombres": ["J. Jara", "C. Prado", "B. Véjar", "D. Troncoso", "R. Campos", "P. Fuentes"],
        "estudiantes_puntajes": [340, 340, 340, 208, 156, 121],
        "estrategias": [
            "Fortalecer habilidades matemáticas de orden superior mediante el análisis grupal de información.",
            "Explicación grupal de errores (fomentar el aprender de las equivocaciones).",
            "Uso intensivo de material concreto para enseñanza de división y resolución de problemas.",
            "Tutorías entre pares lideradas por estudiantes destacados (Jorge Jara, Cristóbal Prado, Benjamín Véjar, Valentina Guzmán, Javiera Romero)."
        ],
        "plan_accion_sugerido": [
            "Implementar banco de actividades durante 8 semanas consecutivas.",
            "Monitoreo de aprendizajes mediante un mini ensayo SIMCE semanal de 5 preguntas.",
            "Intervención focalizada PIE para el grupo de estudiantes prioritarios.",
            "Meta institucional: Aumentar el logro global del curso por sobre el 60% en el próximo ensayo SIMCE."
        ],
        "actividades_aplicables": [
            "Detective de Problemas: Identificar verbalmente información, pregunta y operación antes de resolver.",
            "Feria de Probabilidades: Lanzar monedas/dados, crear tablas de frecuencia e interpretar resultados.",
            "Desafío de Cálculo Mental: 10 minutos diarios con dobles, mitades y complementos a 100.",
            "Estaciones Matemáticas: Rotación en sala cada 15 minutos en cuatro temáticas clave.",
            "Mini Ensayo SIMCE Semanal: Aplicación los viernes con análisis inmediato de distractores.",
            "Banco de Errores: Cada estudiante registra su error, la pregunta y el procedimiento correcto.",
            "Matemática en Contexto: Resolución de situaciones cotidianas (compras, horarios de buses, deportes).",
            "Tutorías entre Pares: Aprovechar el talento de los estudiantes referentes académicos."
        ],
        "conclusion": "El foco estricto de las próximas 8 semanas debe ser la resolución de problemas y la interpretación de datos. La meta institucional es aumentar el logro global por sobre el 60%."
    },
    "6° A_LEN": {
        "resultados_generales": "El curso obtuvo un logro global de 61,6%, alcanzando un puntaje SIMCE estimado de 260,6 puntos. Participaron 28 estudiantes en la evaluación. Estos resultados muestran un desempeño intermedio, con fortalezas en algunas habilidades de comprensión literal, pero con importantes desafíos en análisis, inferencia e interpretación de textos.",
        "habilidades_labels": ["Evaluar", "Identificar", "Interpretar", "Comprender", "Analizar"],
        "habilidades_data": [71.4, 64.6, 63.1, 60.2, 52.4],
        "fortalezas": ["La habilidad mejor lograda es Evaluar (71,4%), lo que indica que los estudiantes logran reconocer propósitos comunicativos y emitir juicios sobre textos.", "Buen desempeño en Identificar (64,6%), especialmente en preguntas de información explícita.", "Historieta: 86,4%."],
        "debilidades": ["La habilidad con menor rendimiento es Analizar (52,4%), evidenciando dificultades para: extraer conclusiones, relacionar información, analizar lenguaje figurado y comprender causas y consecuencias.", "Poesía: 51,2%."],
        "contenidos_labels": ["Historieta", "Vocabulario", "No Literarios", "Poesía"],
        "contenidos_data": [86.4, 61.6, 61.7, 51.2],
        "preguntas_criticas": "Preguntas de inferencia de hablante lírico y análisis bajo el 35%. (P15: 7,1%, P13: 21,4%).",
        "analisis_estudiantes": "Destacados sobre 400 pts (Raquel Irribarra, Aranza Candia, Constanza Retamal) y un grupo prioritario bajo 200 pts (Jossefa Flores, Bruno Sagredo, Amparo Jaureguy, Josefa Quilodrán) que requiere intervención inmediata.",
        "estudiantes_nombres": ["R. Irribarra", "C. Retamal", "A. Candia", "A. Navarro", "B. Sagredo", "J. Flores"],
        "estudiantes_puntajes": [400, 400, 400, 177, 127, 127],
        "estrategias": [
            "A nivel de aula: Inferencias diarias preguntando ¿Qué quiso decir el autor? y ¿Qué podría pasar después?.",
            "Lectura guiada: Modelar el pensamiento lector exigiendo justificar respuestas con evidencia.",
            "Vocabulario contextual: Programa 'La palabra del día' y uso de raíces y prefijos.",
            "Trabajo específico en Poesía: Enseñar a traducir versos a lenguaje cotidiano e identificar metáforas."
        ],
        "plan_accion_sugerido": [
            "Mayo a Noviembre: Ensayos SIMCE semanales.",
            "Mayo-Junio: Foco en inferencias y análisis narrativo.",
            "Julio-Agosto: Foco en lenguaje figurado y poesía.",
            "Septiembre: Foco en textos informativos y vocabulario.",
            "Meta sugerida: 15 minutos diarios de comprensión lectora, 1 texto narrativo semanal, 1 informativo semanal, 1 de poesía quincenal."
        ],
        "actividades_aplicables": [
            "Detectives de Pistas: Subrayar evidencia y responder cómo lo saben.",
            "Tribunal de Personajes: Un grupo defiende al personaje literario y otro lo cuestiona con evidencia.",
            "Transforma el Poema: Reescribir lenguaje poético a lenguaje cotidiano y dibujarlo.",
            "Caza Metáforas: Identificar qué realiza la acción y qué expresa el autor con tarjetas.",
            "El Reportero: Completar organizador gráfico de noticias (Qué, Dónde, Cuándo, Por qué).",
            "SIMCE de 10 minutos: 3 veces por semana con corrección inmediata y explicación de distractores.",
            "La Palabra Misteriosa: Deducir significados de palabras complejas integradas en párrafos.",
            "Semáforo de Comprensión: Monitoreo rápido de entendimiento post lectura."
        ],
        "conclusion": "El curso es capaz de sobrepasar los 280 puntos SIMCE si se nivela a los estudiantes bajo 200 puntos y se trabaja quincenalmente la comprensión de poesía y metáforas."
    },
    "6° B_LEN": {
        "resultados_generales": "El curso obtuvo un 55,8% de logro global, alcanzando un puntaje SIMCE estimado de 240, resultado inferior a lo esperado para el nivel y que evidencia importantes desafíos en comprensión lectora, análisis e interpretación de textos. El curso presenta un desempeño descendido, observándose una brecha importante entre estudiantes de alto rendimiento y un grupo significativo de estudiantes con puntajes muy bajos.",
        "habilidades_labels": ["Identificar", "Evaluar", "Interpretar", "Analizar", "Comprender"],
        "habilidades_data": [62.0, 55.9, 55.6, 50.8, 50.5],
        "fortalezas": ["La habilidad más desarrollada es Identificar (62,0%), demostrando que los estudiantes logran localizar información explícita.", "Historieta (67,6%)."],
        "debilidades": ["Comprender (50,5%) y Analizar (50,8%). Están directamente relacionadas con inferencias, relación entre ideas, justificación de respuestas.", "Deficiencia crítica en el OA 6 (Textos no literarios: 35,3%).", "Poesía (49,5%)."],
        "contenidos_labels": ["Historieta", "Narrativa", "Vocabulario", "Textos No Literarios"],
        "contenidos_data": [67.6, 56.1, 54.4, 52.9],
        "preguntas_criticas": "Preguntas ligadas a textos periodísticos y argumentativos (inferir idea principal) registraron tasas de logro en torno al 20% (P15, P13).",
        "analisis_estudiantes": "Destacados como Clara Loaiza y Renato Muñoz (371 pts) contrastan con 10 estudiantes bajo 190 pts. Urge intervenir a Benjamín Hormazábal (100 pts), Raimundo Ortega (111 pts) y Tomás Vásquez (123 pts).",
        "estudiantes_nombres": ["C. Loaiza", "R. Muñoz", "P. Méndez", "A. Navarro", "H. Sepúlveda", "T. Vásquez", "B. Hormazábal"],
        "estudiantes_puntajes": [371, 371, 356, 172, 153, 123, 100],
        "estrategias": [
            "Prioridad 1: Fortalecer comprensión lectora profunda e inferencias.",
            "Prioridad 2: Trabajar sistemáticamente poesía y lenguaje figurado.",
            "Prioridad 3: Desarrollar análisis de textos informativos comparando información.",
            "Prioridad 4: Implementar reforzamiento focalizado y exclusivo para el grupo bajo 200 puntos."
        ],
        "plan_accion_sugerido": [
            "Implementar Plan Semanal Fijo: Lunes (Inferencias), Martes (Poesía), Miércoles (Noticias), Jueves (Evidencias), Viernes (Ensayo).",
            "Trabajo focalizado con grupo de riesgo: 3 veces por semana lectura guiada y fluidez.",
            "Meta proyectada: Aumentar 20 a 30 puntos SIMCE si se ejecuta la planificación de forma sistemática."
        ],
        "actividades_aplicables": [
            "Taller 'Detectives de Inferencias': 15 minutos diarios subrayando pistas de textos breves.",
            "Cuaderno de Evidencias: Formato de 'Pregunta -> Mi Respuesta -> Evidencia textual'.",
            "Laboratorio de Poesía: Explicar metáforas y transformar versos a lenguaje cotidiano (2x semana).",
            "Desarmando la Noticia: Completar cuadro estructurado atacando el OA más descendido.",
            "¿Quién tiene la razón?: Debate grupal evaluando si la noticia entrega información suficiente.",
            "Vocabulario Contextual: Rutina diaria obligatoria de 5 minutos al inicio de la clase.",
            "SIMCE Express: 5 preguntas tipo prueba 3 veces por semana con revisión inmediata.",
            "Intervención focalizada PIE: Trabajo en grupos pequeños para decodificación y fluidez."
        ],
        "conclusion": "La prioridad absoluta es el OA 6 (Textos no literarios). El curso necesita rutinas altamente estructuradas y repetitivas para nivelar la enorme dispersión académica."
    },
    "6° A_MAT": {
        "resultados_generales": "El curso de 6° Básico A obtuvo un logro global de 35,7% y un puntaje SIMCE estimado de 242,4 puntos, evidenciando resultados descendidos y una importante necesidad de fortalecimiento de los aprendizajes matemáticos fundamentales. Participaron 38 estudiantes.",
        "habilidades_labels": ["Identificar", "Patrones", "Comprender", "Calcular", "Analizar"],
        "habilidades_data": [40.8, 34.5, 33.3, 31.6, 30.9],
        "fortalezas": ["Ningún eje supera el 45% de logro. El 'mejor' desempeño relativo se encuentra en Razones y Porcentajes (42,5%)."],
        "debilidades": ["Analizar (30,9%), Calcular (31,6%) y Comprender (33,3%).", "Déficit alarmante en problemas con fracciones equivalentes y números mixtos (29,8%).", "Resolución de problemas con fracciones y decimales (24,6%)."],
        "contenidos_labels": ["Razones/Porc.", "Números", "Patrones", "Fracciones/Dec."],
        "contenidos_data": [42.5, 38.3, 34.5, 31.1],
        "preguntas_criticas": "24 de las 35 preguntas del ensayo tuvieron menos de un 40% de acierto. Se evidencian lagunas de aprendizaje de años anteriores.",
        "analisis_estudiantes": "Polarización extrema. 8 estudiantes excelentes (Raquel Irribarra, Max Veloso, Constanza Retamal) y un bloque de 12 estudiantes en estado de urgencia bajo los 200 puntos (9 de ellos con el mínimo de 100 puntos basales).",
        "estudiantes_nombres": ["R. Irribarra", "M. Veloso", "C. Retamal", "J. Flores", "J. Aceitón", "M. Dedes", "J. Leal"],
        "estudiantes_puntajes": [400, 400, 367, 187, 100, 100, 100],
        "estrategias": [
            "Retroceder el currículum temporalmente para reparar operatoria básica y cálculo mental.",
            "Uso obligatorio y constante de material concreto para comprender fracciones y razones.",
            "Monitoreo individual semanal del grupo de estudiantes en riesgo extremo.",
            "Implementación de tutorías entre pares como motor principal de aprendizaje en aula."
        ],
        "plan_accion_sugerido": [
            "Asignar a los 8 estudiantes destacados como tutores del grupo descendido.",
            "Establecer grupos de reforzamiento segregados y diferenciados.",
            "Meta directiva a 8 semanas: elevar el logro global a 50% enfocando el trabajo en fracciones y álgebra."
        ],
        "actividades_aplicables": [
            "Taller 'Fracciones en Acción': Uso de pizzas fraccionadas, barras y comparación de equivalencias.",
            "Estaciones Matemáticas: Rotación cada 15 min (Fracciones, Porcentajes, Patrones, Adición).",
            "Detectives de Errores: Presentar problemas mal resueltos para que el alumno detecte el fallo y lo explique.",
            "Desafío de Ecuaciones: Resolver usando balanzas matemáticas y tarjetas con incógnitas.",
            "Rutina '15 Minutos SIMCE': 3 preguntas tipo prueba al inicio de cada clase con corrección metodológica.",
            "Feria de Porcentajes: Uso de catálogos y publicidad real para calcular descuentos.",
            "Campeonato de Cálculo Mental: Práctica de multiplicaciones y divisiones por 10 minutos.",
            "El Problema de la Semana: Foco estricto en metodología de resolución (subrayar, pensar, justificar)."
        ],
        "conclusion": "Emergencia académica. Modificación de la planificación y apoyo PIE constante para el grupo bajo."
    },
    "6° B_MAT": {
        "resultados_generales": "El curso obtuvo un 44,5% de logro global y una proyección de 251,4 puntos SIMCE, resultado que evidencia la necesidad de fortalecer especialmente la resolución de problemas, el razonamiento matemático y el trabajo con fracciones, porcentajes y ecuaciones.",
        "habilidades_labels": ["Comprender", "Calcular", "Resolver Probl.", "Analizar", "Identificar"],
        "habilidades_data": [40.9, 39.8, 36.7, 36.3, 35.1],
        "fortalezas": ["Porcentajes (58,1%)", "Factores y múltiplos (54,0%)", "Razones (51,6%)"],
        "debilidades": ["Resolución de problemas con fracciones y decimales (OA 8): 23,7%.", "Estrategias de cálculo mental (OA 2 de 5° básico): 32,3%.", "Ecuaciones de primer grado (OA 11): 41,9%."],
        "contenidos_labels": ["Porcentajes", "Factores", "Ecuaciones", "Fracciones"],
        "contenidos_data": [58.1, 54.0, 41.9, 23.7],
        "preguntas_criticas": "15 preguntas bajo el 40% de logro, concentrándose mayoritariamente en números mixtos, transferencia a situaciones nuevas y fracciones.",
        "analisis_estudiantes": "Destacados: Rafael Vargas (325 pts) y César Jara (318 pts). Grupo de 9 estudiantes en riesgo, destacando Edgardo Lezana (167 pts). Existe una gran 'masa intermedia' (15 alumnos) que son la clave para la mejora.",
        "estudiantes_nombres": ["R. Vargas", "C. Jara", "P. Méndez", "T. Vásquez", "B. Hormazábal", "A. Navarro", "H. Sepúlveda"],
        "estudiantes_puntajes": [325, 318, 299, 208, 201, 194, 177],
        "estrategias": [
            "Focalizar fuertemente la enseñanza en la 'masa intermedia' (estudiantes entre 40% y 55% de logro).",
            "Trabajo sistemático exclusivo en resolución de problemas contextualizados.",
            "Abordar el concepto de fracciones de forma visual, concreta y manipulable.",
            "Apoyo sistemático en cálculo mental básico."
        ],
        "plan_accion_sugerido": [
            "Implementar Tutorías entre pares utilizando a estudiantes sobre 280 puntos como guías.",
            "Reforzamiento focalizado para estudiantes bajo 230 puntos con coordinación familiar.",
            "Evaluaciones formativas semanales para asegurar la apropiación de fracciones y decimales."
        ],
        "actividades_aplicables": [
            "Tutorías pares: Trabajo en sala guiado por alumnos destacados en grupos de 4.",
            "Clínica de Fracciones: Estaciones de trabajo práctico y concreto con regletas numéricas.",
            "Rutinas de Estrategias de resolución: Fomento de pasos lógicos antes del cálculo algorítmico.",
            "Cálculo mental sistemático: Actividad de inicio de clases orientada a nivelar habilidades de 5° básico.",
            "Análisis de ejercicios resueltos: Para fortalecer la capacidad de justificar procedimientos."
        ],
        "conclusion": "La oportunidad de oro del 6° B es su grupo intermedio. Nivelando sus vacíos en fracciones y razonamiento, el curso puede sobrepasar rápidamente los 270 puntos SIMCE."
    },
    "2° Medio A_LEN": {
        "resultados_generales": "El curso obtuvo un 53,7% de logro global, alcanzando un puntaje SIMCE estimado de 259,8 puntos, resultado que evidencia un desempeño medio, con fortalezas en comprensión de textos informativos, pero importantes desafíos en interpretación, argumentación y análisis literario.",
        "habilidades_labels": ["Evaluar", "Identificar", "Interpretar", "Explicar", "Analizar"],
        "habilidades_data": [64.7, 58.1, 50.8, 50.0, 49.4],
        "fortalezas": ["La habilidad mejor desarrollada es Evaluar (64,7%), lo que indica que los estudiantes logran emitir juicios frente a textos.", "Textos informativos (65,5%)."],
        "debilidades": ["La habilidad más descendida es Analizar (49,4%).", "Textos argumentativos (48,5%): les cuesta identificar tesis, argumentos válidos y falacias.", "Dificultad estructural en justificar respuestas con evidencia del texto."],
        "contenidos_labels": ["Informativos", "Vocabulario", "Literarios", "Argumentativos"],
        "contenidos_data": [65.5, 54.1, 51.0, 48.5],
        "preguntas_criticas": "9 preguntas bajo el 40% de logro. Las más críticas evalúan la distinción entre hechos y opiniones, reconocimiento de contraargumentos y análisis de personajes.",
        "analisis_estudiantes": "Alta dispersión. Excelencia en Diana Landaeta (372), Martín Bustamante (358) y Camila Aldana (344). Grupo de riesgo crónico: Agustina San Martín (146), Clemente Sánchez (159), Magdalena González (171) y David Castillo (194).",
        "estudiantes_nombres": ["D. Landaeta", "M. Bustamante", "C. Aldana", "D. Castillo", "M. González", "C. Sánchez", "A. San Martín"],
        "estudiantes_puntajes": [372, 358, 344, 194, 171, 159, 146],
        "estrategias": [
            "Priorizar comprensión y producción argumentativa oral y escrita.",
            "Entrenamiento explícito en la estructura argumentativa (Tesis-Base-Garantía-Respaldo).",
            "Exigir sistemáticamente inferencias y la justificación de respuestas con citas del texto.",
            "Incorporar preguntas tipo PAES en todas las unidades de aprendizaje regulares."
        ],
        "plan_accion_sugerido": [
            "Desarrollar un Taller PAES-SIMCE semanal enfocado en distractores.",
            "Implementar reforzamiento específico y tutorías para los 4 estudiantes bajo 200 puntos.",
            "Fomentar la escritura argumentativa breve una vez por semana como rutina de salida."
        ],
        "actividades_aplicables": [
            "Detectives de la Argumentación: Identificar tesis, argumentos y evidencia en columnas de opinión.",
            "Debate Express: Fomentar argumentación oral estructurada en equipos a favor y en contra.",
            "Desarmando una Falacia: Analizar ejemplos reales de publicidad o redes sociales para buscar errores lógicos.",
            "Círculos Literarios: Discutir textos asumiendo roles (Analista, Buscador de símbolos, Crítico).",
            "Juicio a los Personajes: Analizar motivaciones y defender/acusar con evidencia literaria.",
            "Teatro y Análisis: Representar escenas y analizar conflictos dramáticos.",
            "Taller PAES-SIMCE: Trabajar inferencias y evaluación crítica 15 minutos dos veces por semana.",
            "Cuaderno de Evidencias: Justificar cada respuesta escrita citando literalmente el texto.",
            "Comparación de Fuentes: Evaluar dos noticias sobre un mismo hecho detectando sesgos.",
            "Escritura Argumentativa Semanal: Textos breves con coevaluación entre pares."
        ],
        "conclusion": "Curso con gran potencial en evaluación crítica. Focalizando la intervención en la lectura de ensayos y textos argumentativos, pueden proyectarse sobre los 280 puntos SIMCE."
    },
    "2° Medio B_LEN": {
        "resultados_generales": "El curso obtuvo un 46,8% de logro global, alcanzando un puntaje SIMCE estimado de 234,6 puntos, resultado que evidencia un desempeño significativamente descendido y que requiere una intervención pedagógica prioritaria para fortalecer las habilidades lectoras evaluadas por SIMCE y PAES.",
        "habilidades_labels": ["Informativos", "Evaluar", "Identificar", "Interpretar", "Analizar"],
        "habilidades_data": [56.3, 52.8, 49.6, 44.6, 44.4],
        "fortalezas": ["Textos informativos (56,3%)", "Logran extraer información básica y rastrear datos explícitos en noticias simples."],
        "debilidades": ["Habilidades de orden superior muy bajas: Analizar (44,4%) e Interpretar (44,6%).", "Texto argumentativo en nivel crítico (41,2%).", "Falla sistémica en deducción, inferencia global y vocabulario contextual abstracto."],
        "contenidos_labels": ["Informativos", "Vocabulario", "Literarios", "Argumentativos"],
        "contenidos_data": [56.3, 47.9, 44.9, 41.2],
        "preguntas_criticas": "13 preguntas bajo 40%. La P24 (11,1%) y P6 (13,9%) muestran que los estudiantes contestan al azar frente a preguntas de inferencia de tono, actitud del emisor y propósito implícito.",
        "analisis_estudiantes": "Contraste brutal. 7 alumnos destacados (Florencia Reyes 385 pts) frente a 14 estudiantes en riesgo severo bajo 200 pts, destacando Sebastián Pacheco (100), Mateo Retamal (100) y Josefa Sáez (100).",
        "estudiantes_nombres": ["F. Reyes", "M. Aravena", "J. Contreras", "M. Ferrada", "M. Matamala", "S. Pacheco", "M. Retamal"],
        "estudiantes_puntajes": [385, 356, 356, 160, 135, 100, 100],
        "estrategias": [
            "Retomar de urgencia las estrategias de comprensión básica (subrayado, notas al margen, resumen de párrafos).",
            "Fortalecer textos argumentativos como prioridad uno.",
            "Enseñanza directa y modelada de inferencias locales y globales.",
            "Mejorar comprensión de textos narrativos y dramáticos analizando conflictos."
        ],
        "plan_accion_sugerido": [
            "Conformar un grupo prioritario obligatorio con los 14 estudiantes bajo 200 puntos.",
            "Implementar lecturas guiadas en grupos pequeños para el grupo de riesgo.",
            "Realizar seguimiento semanal y aplicar ensayos breves quincenales a todo el nivel."
        ],
        "actividades_aplicables": [
            "Descubriendo la Tesis: Completar fichas identificando argumentos y posturas en editoriales breves.",
            "Debate Académico: Defender posturas utilizando evidencias y refutando argumentos contrarios.",
            "Cazadores de Falacias: Analizar descalificaciones, estereotipos y falsas causas en fake news.",
            "Juicio Literario: Análisis profundo de personajes, evaluando alternativas a sus acciones.",
            "Ficha de Análisis Narrativo: Trabajar sistemáticamente el conflicto, motivación y tema central.",
            "Taller de Inferencias: Cuestionar constantemente '¿Qué quiso decir el autor?' y pedir evidencia.",
            "PAES-SIMCE Semanal: Dos veces por semana, aplicar 8-10 preguntas con justificación obligatoria.",
            "Comparación de Fuentes: Evaluar el enfoque y la intención comunicativa de distintas noticias.",
            "Escritura Argumentativa: Textos breves con coevaluación y rúbricas.",
            "Trabajo con Vocabulario Contextual: Rutina diaria de 5 minutos deduciendo el sentido en la oración."
        ],
        "conclusion": "El curso necesita un reseteo metodológico total. Si se logra disciplinar el proceso lector y enseñar sistemáticamente a inferir, el curso puede revertir este puntaje y subir entre 25 y 35 puntos."
    },
    "2° Medio A_MAT": {
        "resultados_generales": "El curso II° Medio A obtuvo un logro global de 31,0% y un puntaje SIMCE estimado de 273,6 puntos, resultado que evidencia un desempeño insuficiente respecto de los aprendizajes esperados para el nivel. Participaron 32 estudiantes efectivos.",
        "habilidades_labels": ["Comprender", "Representar", "Analizar", "Aplicar", "Resolver Probl."],
        "habilidades_data": [38.1, 35.2, 32.7, 30.7, 23.8],
        "fortalezas": ["Comprender (38,1%)", "Números Reales y Potencias (33,3%)", "Probabilidad y Estadística (33,1%)"],
        "debilidades": ["Resolver Problemas (23,8%) es la habilidad en mayor crisis.", "Logaritmos y Funciones (25,6%)", "Álgebra y Ecuaciones (27,5%). Deficiencias en sistemas de ecuaciones y productos notables."],
        "contenidos_labels": ["Números", "Estadística", "Geometría", "Logaritmos"],
        "contenidos_data": [33.3, 33.1, 32.4, 25.6],
        "preguntas_criticas": "28 de 35 preguntas bajo el 40%. Evidencia falta de comprensión absoluta del Teorema de Tales y resolución de sistemas 2x2.",
        "analisis_estudiantes": "Siete alumnos destacados esconden la dura realidad: 13 alumnos están bajo 238 puntos y 28 tienen menos del 50% de logro. Curso fracturado.",
        "estudiantes_nombres": ["J. Pérez", "S. Araya", "I. Coronado", "M. Castro", "M. González", "F. Vega"],
        "estudiantes_puntajes": [400, 400, 386, 224, 209, 193],
        "estrategias": [
            "Fortalecer prioritariamente Álgebra, Funciones, Logaritmos y Resolución de Problemas.",
            "Incorporar rutinas de ejercitación sistemática diarias (no solo clases teóricas).",
            "Trabajo diferenciado y seguimiento focalizado estricto para estudiantes con mayores dificultades.",
            "Utilizar siempre secuencias ordenadas de pasos para enfrentar problemas matemáticos."
        ],
        "plan_accion_sugerido": [
            "Plan de choque de 8 semanas para elevar la Resolución de Problemas a 40% y Álgebra a 45%.",
            "Implementar Tutorías formales semanales dirigidas por los estudiantes destacados (grupos de 4).",
            "Monitoreo constante de asistencia y guías diferenciadas para el grupo de riesgo extremo."
        ],
        "actividades_aplicables": [
            "Rutina PAES Matemática: 15 minutos diarios con problemas de análisis y respuesta directa.",
            "Taller de Logaritmos y Potencias: Estaciones de trabajo abordando propiedades y transformación.",
            "Clínica de Errores: Aprender de las equivocaciones analizando las preguntas más descendidas del ensayo.",
            "Resolución de Problemas Paso a Paso: Aplicación rígida del método Comprender-Planificar-Resolver-Comprobar.",
            "Desafío Semanal PAES: 10 preguntas con corrección inmediata de distractores.",
            "Taller de Sistemas de Ecuaciones: Contextualización de problemas (método gráfico y reducción).",
            "Geometría Aplicada: Construcción de escalas, planos y cálculo de alturas usando sombras en el colegio.",
            "Tutorías Entre Pares: Revisión colaborativa de ejercicios y procedimientos.",
            "Matemática en Contexto Real: Uso de interés bancario, créditos, descuentos y gráficos económicos."
        ],
        "conclusion": "El curso requiere un cambio metodológico drástico: la matemática debe salir de la pizarra teórica y aplicarse a contextos reales de forma procedimental."
    },
    "2° Medio B_MAT": {
        "resultados_generales": "El curso obtuvo un 30,6% de logro global y una proyección de 223,8 puntos SIMCE, evidenciando un desempeño descendido en la mayoría de los ejes y habilidades evaluadas. Los resultados reflejan dificultades importantes en el manejo de contenidos de Números Reales, Potencias, Raíces, Geometría y resolución de problemas matemáticos.",
        "habilidades_labels": ["Resolver Probl.", "Analizar", "Aplicar", "Comprender", "Calcular"],
        "habilidades_data": [37.4, 32.2, 30.5, 30.0, 24.4],
        "fortalezas": ["Probabilidad y Estadística (37,4%) es el eje menos afectado.", "Capacidad aceptable de extraer información de gráficos simples y directos."],
        "debilidades": ["Habilidad de Calcular (24,4%) totalmente descendida.", "Operaciones básicas con raíces (15,8%) y potencias de base racional (10,5%).", "Desconocimiento generalizado de función afín (18,4%)."],
        "contenidos_labels": ["Estadística", "Álgebra", "Geometría", "Raíces/Potencias"],
        "contenidos_data": [37.4, 34.2, 32.0, 15.8],
        "preguntas_criticas": "El 82% de la prueba (29 preguntas) obtuvo menos del 40% de logro. Las preguntas de desarrollo numérico directo tienen tasas de acierto entre 0% y 10%.",
        "analisis_estudiantes": "Brecha gigantesca e inmanejable. Solo dos destacados contrastan violentamente con 36 estudiantes bajo el 50% de logro. Riesgo extremo en operatoria fundamental.",
        "estudiantes_nombres": ["G. Arancibia", "Á. Fuentes", "A. Ramos", "M. Ferrada", "J. Pérez", "S. Pacheco", "V. Villar"],
        "estudiantes_puntajes": [293, 293, 260, 208, 194, 194, 186],
        "estrategias": [
            "Retroceso curricular obligatorio: reparar cálculo, signos, raíces y álgebra de 7° a I° Medio antes de abordar II° Medio.",
            "Fortalecer la resolución de problemas lúdicos y colaborativos para recuperar la motivación.",
            "Incrementar drásticamente las oportunidades de práctica guiada supervisada en el aula.",
            "Implementar seguimiento diferenciado y clínico al extenso grupo prioritario."
        ],
        "plan_accion_sugerido": [
            "Ejecutar un 'Plan Intensivo para Estudiantes Prioritarios' con dos sesiones extra semanales de reforzamiento.",
            "Sesión 1 dedicada solo a operatoria, raíces y potencias. Sesión 2 enfocada en problemas y geometría.",
            "Establecer la meta de elevar el logro global a 45% durante el segundo semestre."
        ],
        "actividades_aplicables": [
            "Desafío Matemático Diario: 10 minutos iniciales para operatoria, potencias y ecuaciones breves.",
            "Escape Room Matemático: Trabajo colaborativo donde resolver ejercicios entrega claves para avanzar.",
            "Dominó Matemático: Tarjetas para unir equivalencias de potencias y raíces de forma visual.",
            "Proyecto 'Diseñemos un Parque' (ABP): Integrar geometría, áreas, proporcionalidad y homotecia a escala.",
            "Tutorías entre pares: Estudiantes destacados asumen grupos de 4 compañeros del sector crítico.",
            "Matemática en la Vida Real: Informes breves explicando créditos bancarios o descuentos comerciales.",
            "Laboratorio de Errores: Analizar ejercicios incorrectamente resueltos y explicar el fallo lógico.",
            "Estaciones de Aprendizaje: Rotación cada 15 minutos en módulos de raíces, ecuaciones, geometría y probabilidad.",
            "Problema SIMCE de la Semana: Resolver problemas de alta complejidad en grupo todos los lunes."
        ],
        "conclusion": "La intervención debe ser inmediata y radical. Es virtualmente imposible avanzar en el currículum regular de II° Medio sin antes detenerse a reparar y nivelar las competencias numéricas basales del curso."
    }
}

FALLBACK_CURSO = {
    "resultados_generales": "Datos en proceso de tabulación por Unidad Técnico Pedagógica.",
    "habilidades_labels": ["Habilidad 1", "Habilidad 2", "Habilidad 3"], "habilidades_data": [0, 0, 0],
    "fortalezas": ["En evaluación por departamento."], "debilidades": ["En evaluación técnica."],
    "contenidos_labels": ["Contenido A", "Contenido B"], "contenidos_data": [0, 0],
    "preguntas_criticas": "Información disponible en reporte físico detallado.",
    "analisis_estudiantes": "Revisar matriz de datos anexa en secretaría académica.",
    "estudiantes_nombres": ["Sin Datos"], "estudiantes_puntajes": [0],
    "estrategias": ["Aplicar lineamientos generales del departamento y orientaciones del Mineduc."],
    "plan_accion_sugerido": ["Definir plan estratégico en el próximo consejo técnico de profesores."],
    "actividades_aplicables": ["Práctica guiada general.", "Reforzamiento de habilidades descendidas."],
    "conclusion": "Análisis pendiente de cierre por parte del equipo directivo."
}

ESTUDIANTES = {
    "Agustina Carrasco": {'curso': '2° Medio B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 220 y 240 puntos SIMCE. Grupo con gran potencial de mejora rápida.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Agustina Fernanda Quilodrán": {'curso': '2° Medio A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 237. Resultados descendidos, necesitan apoyo focalizado.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Agustina Maldonado": {'curso': '6° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 223. Grupo de resultados extremadamente bajos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Agustina Munita": {'curso': '2° Medio B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 194. Importantes brechas en contenidos básicos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Agustina Paz Aguirre": {'curso': '2° Medio A', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 376. Dominio superior al promedio.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Agustina Ramos": {'curso': '2° Medio B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 260. Dominio sólido, posibles tutores.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 330. Estudiantes destacados.'},
    "Agustina San Martín": {'curso': '2° Medio A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 146. Grupo prioritario.'},
    "Agustín Gajardo": {'curso': '4° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje proyectado: 221. Seguimiento focalizado.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 126. Intervención intensiva y lectura guiada.'},
    "Agustín Troncoso": {'curso': '4° B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 288. Referentes académicos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Alonso Navarro": {'curso': '6° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 194. Intervención prioritaria y uso de material concreto.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 172. Intervención prioritaria sugerida.'},
    "Alonso Painemilla": {'curso': '6° A', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 346. Evidencian dominio importante, posibles tutores.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Alonso Philips": {'curso': '6° B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 40% y 55% de logro. Principal oportunidad de mejora.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Alonso Rosales": {'curso': '2° Medio B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 244. Dominio sólido, posibles tutores.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Amanda Batarce": {'curso': '2° Medio B', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 330. Estudiantes destacados.'},
    "Amara Ignacia Manríquez": {'curso': '2° Medio A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 224. Resultados descendidos, necesitan apoyo focalizado.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Amparo Jaureguy": {'curso': '6° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 140. Requiere intervención focalizada inmediata.'},
    "Antonella Navarro": {'curso': '6° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 177. Requiere intervención focalizada inmediata.'},
    "Antonia Labrador": {'curso': '6° B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 40% y 55% de logro. Principal oportunidad de mejora.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Antonia Manzano": {'curso': '4° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 114. Intervención intensiva y lectura guiada.'},
    "Aranza Candia": {'curso': '6° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 400. Alto desempeño.'},
    "Baltazar Jaque": {'curso': '6° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 331. Alto desempeño.'},
    "Benjamín Hormazábal": {'curso': '6° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 201. Intervención prioritaria y uso de material concreto.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 100. Intervención prioritaria sugerida.'},
    "Benjamín Ovalle": {'curso': '4° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje proyectado: 244. Seguimiento focalizado.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Benjamín Véjar": {'curso': '4° B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 340. Referentes académicos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Borja Acuña": {'curso': '6° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 302. Alto desempeño.'},
    "Bruno Sagredo": {'curso': '6° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 127. Requiere intervención focalizada inmediata.'},
    "Camila Aldana": {'curso': '2° Medio A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 344. Desempeño sobresaliente.'},
    "Camilo Contreras": {'curso': '4° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 330. Desempeño sobresaliente.'},
    "Carlos García": {'curso': '6° B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 40% y 55% de logro. Principal oportunidad de mejora.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 181. Intervención prioritaria sugerida.'},
    "Catalina Andrea Román": {'curso': '2° Medio A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 237. Resultados descendidos, necesitan apoyo focalizado.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Catalina Hormazábal": {'curso': '2° Medio B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 249. Dominio sólido, posibles tutores.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Catalina Mancilla": {'curso': '2° Medio B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 220 y 240 puntos SIMCE. Grupo con gran potencial de mejora rápida.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Catalina Reyes": {'curso': '2° Medio B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 220 y 240 puntos SIMCE. Grupo con gran potencial de mejora rápida.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 121. Situación crítica, requieren reforzamiento intensivo.'},
    "Catalina Rodríguez": {'curso': '6° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 380. Alto desempeño.'},
    "Clara Loaiza": {'curso': '6° B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 40% y 55% de logro. Principal oportunidad de mejora.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 371. Alto desempeño.'},
    "Clemente Sánchez": {'curso': '2° Medio A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 159. Grupo prioritario.'},
    "Constanza Retamal": {'curso': '6° A', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 367. Evidencian dominio importante, posibles tutores.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 400. Alto desempeño.'},
    "Cristóbal Prado": {'curso': '4° B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 340. Referentes académicos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "César Jara": {'curso': '6° B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 318. Buen dominio de procedimientos.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 330. Alto desempeño.'},
    "David Castillo": {'curso': '2° Medio A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 194. Grupo prioritario.'},
    "Diana Landaeta": {'curso': '2° Medio A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 372. Desempeño sobresaliente.'},
    "Diego Bustamante": {'curso': '4° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 400. Desempeño sobresaliente.'},
    "Diego Painemilla": {'curso': '4° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 238. Evaluar necesidades educativas o hábitos de estudio.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 188. Apoyo intensivo y monitoreo semanal.'},
    "Dominga Carvajal": {'curso': '6° B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 282. Buen dominio de procedimientos.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 343. Alto desempeño.'},
    "Dominga Troncoso": {'curso': '4° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 208. Evaluar necesidades educativas o hábitos de estudio.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 188. Apoyo intensivo y monitoreo semanal.'},
    "Domingo Pino": {'curso': '2° Medio B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 220 y 240 puntos SIMCE. Grupo con gran potencial de mejora rápida.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Edgardo Lezana": {'curso': '6° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 167. Intervención prioritaria y uso de material concreto.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Elizabeth González": {'curso': '4° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 346. Desempeño sobresaliente.'},
    "Emilia Becerra": {'curso': '6° A', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 325. Evidencian dominio importante, posibles tutores.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Emilia Muñoz": {'curso': '6° B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 40% y 55% de logro. Principal oportunidad de mejora.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 318. Alto desempeño.'},
    "Emilia Sepúlveda": {'curso': '4° B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 293. Referentes académicos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Emilio Rojas": {'curso': '2° Medio B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 220 y 240 puntos SIMCE. Grupo con gran potencial de mejora rápida.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 184. Situación crítica, requieren reforzamiento intensivo.'},
    "Emma Recasens": {'curso': '6° A', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 336. Evidencian dominio importante, posibles tutores.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Felipe Iturriaga": {'curso': '2° Medio B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 201. Importantes brechas en contenidos básicos.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 195. Situación crítica, requieren reforzamiento intensivo.'},
    "Fernanda Cisternas": {'curso': '6° B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 40% y 55% de logro. Principal oportunidad de mejora.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Fernanda Concha": {'curso': '2° Medio B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 208. Importantes brechas en contenidos básicos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Fernanda Josefa Deick": {'curso': '2° Medio A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 237. Resultados descendidos, necesitan apoyo focalizado.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Florencia Reyes": {'curso': '2° Medio B', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 385. Estudiantes destacados.'},
    "Francisco Tomás Vega": {'curso': '2° Medio A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 193. Resultados descendidos, necesitan apoyo focalizado.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Gaspar Arancibia": {'curso': '2° Medio B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 293. Dominio sólido, posibles tutores.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Gaspar Domingo Vásquez": {'curso': '2° Medio A', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 326. Dominio superior al promedio.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Héctor Sepúlveda": {'curso': '6° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 177. Intervención prioritaria y uso de material concreto.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 153. Intervención prioritaria sugerida.'},
    "Ignacia Albornoz": {'curso': '6° B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 40% y 55% de logro. Principal oportunidad de mejora.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 307. Alto desempeño.'},
    "Isabella Yáñez": {'curso': '4° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 171. Intervención intensiva y lectura guiada.'},
    "Isidora Alarcón": {'curso': '6° B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 40% y 55% de logro. Principal oportunidad de mejora.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 133. Intervención prioritaria sugerida.'},
    "Isidora Cisternas": {'curso': '4° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 121. Evaluar necesidades educativas o hábitos de estudio.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Isidora Coronado": {'curso': '2° Medio A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 319. Desempeño sobresaliente.'},
    "Isidora Julieta Coronado": {'curso': '2° Medio A', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 386. Dominio superior al promedio.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Isidora Pincheira": {'curso': '6° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 302. Alto desempeño.'},
    "Isis Durán": {'curso': '6° B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 40% y 55% de logro. Principal oportunidad de mejora.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Javiera Contreras": {'curso': '2° Medio B', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 356. Estudiantes destacados.'},
    "Javiera Romero": {'curso': '4° B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 311. Referentes académicos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Joaquín Eduardo Guerrero": {'curso': '2° Medio A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 224. Resultados descendidos, necesitan apoyo focalizado.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Joaquín Jara": {'curso': '4° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 100. Intervención intensiva y lectura guiada.'},
    "Joaquín Leal": {'curso': '6° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 100. Grupo de resultados extremadamente bajos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Joaquín Ovalle": {'curso': '2° Medio B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 208. Importantes brechas en contenidos básicos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Joaquín Sandoval": {'curso': '4° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 330. Desempeño sobresaliente.'},
    "Jorge Jara": {'curso': '4° B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 340. Referentes académicos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Jorge Tillería": {'curso': '4° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 171. Intervención intensiva y lectura guiada.'},
    "Josefa Aceitón": {'curso': '6° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 100. Grupo de resultados extremadamente bajos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Josefa Herrera": {'curso': '6° B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 40% y 55% de logro. Principal oportunidad de mejora.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Josefa Quilodrán": {'curso': '6° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 152. Requiere intervención focalizada inmediata.'},
    "Josefa Sáez": {'curso': '2° Medio B', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 100. Situación crítica, requieren reforzamiento intensivo.'},
    "Josefa Vega": {'curso': '6° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 100. Grupo de resultados extremadamente bajos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Jossefa Flores": {'curso': '6° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 187. Grupo de resultados extremadamente bajos.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 127. Requiere intervención focalizada inmediata.'},
    "José Manuel Pérez": {'curso': '2° Medio A', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 400. Dominio superior al promedio.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "José Pedro Jaque": {'curso': '4° B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 288. Referentes académicos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "José Pérez": {'curso': '2° Medio A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 319. Desempeño sobresaliente.'},
    "Joséraul Leiva": {'curso': '2° Medio B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 208. Importantes brechas en contenidos básicos.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 148. Situación crítica, requieren reforzamiento intensivo.'},
    "Juan David Pereira": {'curso': '6° B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 288. Buen dominio de procedimientos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Juan Felipe Pérez": {'curso': '2° Medio B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 194. Importantes brechas en contenidos básicos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Juan Ignacio Alfaro": {'curso': '2° Medio B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 201. Importantes brechas en contenidos básicos.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 330. Estudiantes destacados.'},
    "Juan José Porra": {'curso': '4° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje proyectado: 221. Seguimiento focalizado.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 126. Intervención intensiva y lectura guiada.'},
    "Julieta González": {'curso': '6° B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 40% y 55% de logro. Principal oportunidad de mejora.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 189. Intervención prioritaria sugerida.'},
    "Julieta Rodríguez": {'curso': '2° Medio A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 331. Desempeño sobresaliente.'},
    "Julián Mesa": {'curso': '4° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje proyectado: 208. Seguimiento focalizado.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 171. Intervención intensiva y lectura guiada.'},
    "Karim Najle": {'curso': '2° Medio B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 220 y 240 puntos SIMCE. Grupo con gran potencial de mejora rápida.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 107. Situación crítica, requieren reforzamiento intensivo.'},
    "Laura Verdugo": {'curso': '6° B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 40% y 55% de logro. Principal oportunidad de mejora.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Liam Apolonio": {'curso': '6° A', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 325. Evidencian dominio importante, posibles tutores.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Lucas Benjamín Ibáñez": {'curso': '2° Medio A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 224. Resultados descendidos, necesitan apoyo focalizado.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Lucas Vega": {'curso': '4° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 221. Evaluar necesidades educativas o hábitos de estudio.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Magdalena Andrea González": {'curso': '2° Medio A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 209. Resultados descendidos, necesitan apoyo focalizado.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Magdalena González": {'curso': '2° Medio A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 171. Grupo prioritario.'},
    "Maite Aravena": {'curso': '2° Medio B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 220 y 240 puntos SIMCE. Grupo con gran potencial de mejora rápida.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 356. Estudiantes destacados.'},
    "Maite Méndez": {'curso': '4° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje proyectado: 249. Seguimiento focalizado.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Manuel Sepúlveda": {'curso': '6° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 100. Grupo de resultados extremadamente bajos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Martina Luna": {'curso': '6° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 221. Intervención prioritaria y uso de material concreto.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Martina Pincheira": {'curso': '6° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 189. Requiere intervención focalizada inmediata.'},
    "Martín Augusto Castro": {'curso': '2° Medio A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 224. Resultados descendidos, necesitan apoyo focalizado.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Martín Bustamante": {'curso': '2° Medio A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 358. Desempeño sobresaliente.'},
    "Martín Carvajal": {'curso': '6° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 227. Intervención prioritaria y uso de material concreto.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 162. Intervención prioritaria sugerida.'},
    "Martín Emilio Bustamante": {'curso': '2° Medio A', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 346. Dominio superior al promedio.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Martín Fuentes": {'curso': '2° Medio B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 220 y 240 puntos SIMCE. Grupo con gran potencial de mejora rápida.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 160. Situación crítica, requieren reforzamiento intensivo.'},
    "María Ignacia Vidal": {'curso': '2° Medio B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 220 y 240 puntos SIMCE. Grupo con gran potencial de mejora rápida.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "María Jesús Reyes": {'curso': '2° Medio B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 220 y 240 puntos SIMCE. Grupo con gran potencial de mejora rápida.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 107. Situación crítica, requieren reforzamiento intensivo.'},
    "María Muñoz": {'curso': '6° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 100. Grupo de resultados extremadamente bajos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Mateo Retamal": {'curso': '2° Medio B', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 100. Situación crítica, requieren reforzamiento intensivo.'},
    "Mateo Reyes": {'curso': '4° B', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 215. Apoyo intensivo y monitoreo semanal.'},
    "Mateo Zúñiga": {'curso': '6° B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 276. Buen dominio de procedimientos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Matilde Aedo": {'curso': '2° Medio B', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 172. Situación crítica, requieren reforzamiento intensivo.'},
    "Matías Matamala": {'curso': '2° Medio B', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 135. Situación crítica, requieren reforzamiento intensivo.'},
    "Maximiliano Dedes": {'curso': '6° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 100. Grupo de resultados extremadamente bajos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Maximiliano Ferrada": {'curso': '2° Medio B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 208. Importantes brechas en contenidos básicos.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 160. Situación crítica, requieren reforzamiento intensivo.'},
    "Maximiliano Veloso": {'curso': '6° A', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 400. Evidencian dominio importante, posibles tutores.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 316. Alto desempeño.'},
    "Máximo Alejandro Sepúlveda": {'curso': '2° Medio A', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 326. Dominio superior al promedio.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Máximo Benavides": {'curso': '4° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 121. Evaluar necesidades educativas o hábitos de estudio.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Máximo Rubio": {'curso': '4° B', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 215. Apoyo intensivo y monitoreo semanal.'},
    "Noah Aravena": {'curso': '4° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 330. Desempeño sobresaliente.'},
    "Pablo Muñoz": {'curso': '2° Medio A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 307. Desempeño sobresaliente.'},
    "Pascal Aguilera": {'curso': '6° B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 40% y 55% de logro. Principal oportunidad de mejora.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Pedro Fuentes": {'curso': '4° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 121. Evaluar necesidades educativas o hábitos de estudio.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 156. Apoyo intensivo y monitoreo semanal.'},
    "Pedro Méndez": {'curso': '6° B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 299. Buen dominio de procedimientos.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 356. Alto desempeño.'},
    "Rafael Muñoz": {'curso': '4° A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 171. Intervención intensiva y lectura guiada.'},
    "Rafael Vargas": {'curso': '6° B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 325. Buen dominio de procedimientos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Raffaella Rupertus": {'curso': '6° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 100. Grupo de resultados extremadamente bajos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Raimundo Ortega": {'curso': '6° B', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 111. Intervención prioritaria sugerida.'},
    "Raquel Irribarra": {'curso': '6° A', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 400. Evidencian dominio importante, posibles tutores.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 400. Alto desempeño.'},
    "Rayen Caamaño": {'curso': '6° B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 40% y 55% de logro. Principal oportunidad de mejora.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Renato Albornoz": {'curso': '6° A', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 346. Evidencian dominio importante, posibles tutores.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Renato Mestre": {'curso': '2° Medio B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 249. Dominio sólido, posibles tutores.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Renato Muñoz": {'curso': '6° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 221. Intervención prioritaria y uso de material concreto.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 371. Alto desempeño.'},
    "Rocío Campos": {'curso': '4° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 156. Evaluar necesidades educativas o hábitos de estudio.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Samuel Araya": {'curso': '2° Medio A', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 331. Desempeño sobresaliente.'},
    "Samuel Ignacio Araya": {'curso': '2° Medio A', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 400. Dominio superior al promedio.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Santiago Barra": {'curso': '2° Medio B', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 107. Situación crítica, requieren reforzamiento intensivo.'},
    "Santiago Retamal": {'curso': '6° B', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 343. Alto desempeño.'},
    "Santiago Rodríguez": {'curso': '6° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 100. Grupo de resultados extremadamente bajos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Sara Bobadilla": {'curso': '4° B', 'mat_estado': 'Sin registros', 'mat_notas': 'Sin observaciones cualitativas.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 208. Apoyo intensivo y monitoreo semanal.'},
    "Sebastián Díaz": {'curso': '4° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje proyectado: 238. Seguimiento focalizado.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 182. Intervención intensiva y lectura guiada.'},
    "Sebastián Eduardo Chávez": {'curso': '2° Medio A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 237. Resultados descendidos, necesitan apoyo focalizado.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Sebastián Gutiérrez": {'curso': '6° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 223. Grupo de resultados extremadamente bajos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Sebastián Pacheco": {'curso': '2° Medio B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 194. Importantes brechas en contenidos básicos.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 100. Situación crítica, requieren reforzamiento intensivo.'},
    "Sebastián Quiroz": {'curso': '6° B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 40% y 55% de logro. Principal oportunidad de mejora.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Sofía Aguilera": {'curso': '2° Medio B', 'mat_estado': 'Intermedio', 'mat_notas': 'Entre 220 y 240 puntos SIMCE. Grupo con gran potencial de mejora rápida.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Sofía Mical Guzmán": {'curso': '2° Medio A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 237. Resultados descendidos, necesitan apoyo focalizado.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Sofía Palma": {'curso': '2° Medio B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 244. Dominio sólido, posibles tutores.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Sofía Salgado": {'curso': '2° Medio B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 244. Dominio sólido, posibles tutores.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Tahiel Quintanilla": {'curso': '6° A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 100. Grupo de resultados extremadamente bajos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Tomás Carvajal": {'curso': '6° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 227. Intervención prioritaria y uso de material concreto.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 153. Intervención prioritaria sugerida.'},
    "Tomás Vásquez": {'curso': '6° B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 208. Intervención prioritaria y uso de material concreto.', 'len_estado': 'Riesgo', 'len_notas': 'Puntaje: 123. Intervención prioritaria sugerida.'},
    "Valentina Guzmán": {'curso': '4° B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 311. Referentes académicos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Valentina Ignacia Figueroa": {'curso': '2° Medio A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 237. Resultados descendidos, necesitan apoyo focalizado.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Valentina Martínez": {'curso': '2° Medio B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 208. Importantes brechas en contenidos básicos.', 'len_estado': 'Destacado', 'len_notas': 'Puntaje: 356. Estudiantes destacados.'},
    "Valentina Villar": {'curso': '2° Medio B', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 186. Importantes brechas en contenidos básicos.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Vicente Andrés Vásquez": {'curso': '2° Medio A', 'mat_estado': 'Riesgo', 'mat_notas': 'Puntaje: 224. Resultados descendidos, necesitan apoyo focalizado.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
    "Ámbar Fuentes": {'curso': '2° Medio B', 'mat_estado': 'Destacado', 'mat_notas': 'Puntaje: 293. Dominio sólido, posibles tutores.', 'len_estado': 'Sin registros', 'len_notas': 'Sin observaciones cualitativas.'},
}