# Generated by Django 6.0.5 on 2026-05-28 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoSimce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(choices=[('MAT', 'Matemática'), ('LEN', 'Lenguaje')], max_length=3)),
                ('porcentaje_logro', models.FloatField()),
                ('puntaje_simce', models.FloatField()),
                ('estudiantes_riesgo', models.IntegerField(help_text='Estudiantes bajo 50% de logro')),
                ('preguntas_criticas', models.IntegerField(help_text='Preguntas bajo 40% de acierto')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.curso')),
            ],
        ),
    ]
